### ISSUE TITLE
About 'MinimalAPIs'. The 'var app = builder.AddServices();' method name not very semanty.Bacause it doesn't look like building a 'WebApplication' object.It like add a service.

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Framework#428] opened 2023-02-01 06:11 UTC
The 'var app = builder.AddServices();' method does three thing inside. As follow:
1:  Add 'MinimalAPIs' service
2: Building 'WebApplication' object and add to contianer collection
3: Initing 'MasaApp' class.

It deserves have a better name.

**Comment by doddgu** [comment] 2023-02-03 05:13
@zhenlei520 what do you think?

**Comment by MapleWithoutWords** [comment] 2023-02-03 06:36
My English not is very good,very chinese english.hope you can look understandand.
and about MasaApp this design.
I think and 'Abp vNext' IAbpApplication class design compare,'AbpvNext' design is better.  though it and 'Abp vNext' IAbpApplication class design similar,but 'Abp vNext' can have more extension space

**Comment by MapleWithoutWords** [comment] 2023-02-03 06:42
I will 'MasaApp' class can support extensions. just like 'AbpVNext' same . 
![image](https://user-images.githubusercontent.com/38368335/216530304-3eac1567-e01e-43ba-a3c6-a1cc6ff3baec.png)

**Comment by zhenlei520** [comment] 2023-02-03 07:03
MasaApp is only used to store global configurations. Normally, developers don't need to use it. Although it seems that it is not as elegant as IAbpApplication, because of this, it becomes easier to master it.

**Comment by zhenlei520** [comment] 2023-02-03 07:04
> The 'var app = builder.AddServices();' method does three thing inside. As follow: 1: Add 'MinimalAPIs' service 2: Building 'WebApplication' object and add to contianer collection 3: Initing 'MasaApp' class.
> 
> It deserves have a better name.

AddServices is indeed easy to bring ambiguity, we will try to optimize it later

**Comment by doddgu** [comment] 2023-02-03 07:14
I don't think we can work around the minimalapi map limitation right now.
If we just split the AddServices, it's meaningless.

**Comment by zhenlei520** [comment] 2023-02-03 07:25
> I don't think we can work around the minimalapi map limitation right now. If we just split the AddServices, it's meaningless.

You can try to register to the App through other methods, like `AddControllers`, but the premise is that it is not fixed in `WebApplicationBuilder`. This needs to be confirmed after checking the source code of AspNetCore. At present, there is no guarantee that it can be done.

**Comment by doddgu** [comment] 2023-02-03 07:40
So, what's next?

**Comment by MapleWithoutWords** [comment] 2023-02-03 07:43
> MasaApp is only used to store global configurations. Normally, developers don't need to use it. Although it seems that it is not as elegant as IAbpApplication, because of this, it becomes easier to master it.

I'm understand. Thanks!

**Comment by zhenlei520** [comment] 2023-02-03 07:45
> So, what's next?

I will first determine whether the next plan is feasible and wait for the follow-up results

**Comment by doddgu** [comment] 2023-02-03 07:52
I think just keep the design now. Until minimal api map remove limits.

**Comment by MapleWithoutWords** [comment] 2023-02-03 08:11
I have a suggestion. can refer to my 'NET.AutoApi' this package's design. it can dynamic will service method map to route.but this not is minialapi. this is blog address: https://www.cnblogs.com/norain/p/17049662.html   @zhenlei520

**Comment by MapleWithoutWords** [comment] 2023-02-03 08:21
> I have a suggestion. can refer to my 'NET.AutoApi' this package's design. it can dynamic will service method map to route.but this not is microsoft minialapi's design. this is blog address: https://www.cnblogs.com/norain/p/17049662.html @zhenlei520

the package need Add Mvc depend，it already not is minialapi. for reference only.

**Comment by doddgu** [comment] 2023-02-03 08:44
ServiceBase is not the final form. 2.0 will be the final part of the design.

**Comment by zhenlei520** [comment] 2023-02-03 10:27
The previous consideration was complicated. We can get WebApplication in a simpler way, which only changes the registration method, but does not need to modify the use of ServiceBase, like

![image](https://user-images.githubusercontent.com/9740886/216576756-d6baeb79-328f-4147-942c-a5d93451fc9d.png)

**Comment by doddgu** [comment] 2023-02-05 05:29
It's ok, just another way to use.it.

**Closed** 2023-03-30 15:14 UTC
